### PR TITLE
18 Add fast5 signal summary statistics

### PR DESCRIPTION
**Pull request by jonperdomo**
Implement base signal QC

### CODE REVIEW

**Comment by jonperdomo** [comment]
Dynamic HTML:

image

CSV outputs:

image

**Comment by kaichop** [comment]
Why there are exactly five data points per base? Also skewness and kurtosis
would also be helpful, as well as the number of data points (it should vary
a lot, rather than being 5)

**Comment by jonperdomo** [comment]
@kaichop The value of 5 corresponds to the block stride value, which is the file attribute _"/Analyses/Basecall_1D_000/Summary/basecall_1d_template/block_stride"_

**Comment by jonperdomo** [comment]
@kaichop @umahsn The block stride value is the window for detecting bases: A 1 in the _Move_ boolean array corresponds to a base detected in that window.

**Comment by jonperdomo** [comment]
@kaichop @umahsn I will update the plots to show the signal up until the move table block where the base call occurs so that the entire signal data is shown. Currently I only plot each move table block

**Comment by jonperdomo** [comment]
The signal plot now shows the signal data up until the basecall event:
newplot

**Comment by jonperdomo** [comment]
I added signal length, skewness, and kurtosis to the CSV as well. I used the MATLAB default equations for skewness and kurtosis, and double-checked that my results for these are the same as with MATLAB:
image

**Pull request merged**
